### ISSUE TITLE
load vgg weight error

### ISSUE THREAD

**Issue by SoulCoderCN** [AceCoooool/DSS-pytorch#15]
RuntimeError: Error(s) in loading state_dict for ModuleList:
	Missing key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "5.weight", "5.bias", "7.weight", "7.bias", "10.weight", "10.bias", "12.weight", "12.bias", "14.weight", "14.bias", "17.weight", "17.bias", "19.weight", "19.bias", "21.weight", "21.bias", "24.weight", "24.bias", "26.weight", "26.bias", "28.weight", "28.bias". 
	Unexpected key(s) in state_dict: "features.0.weight", "features.0.bias", "features.2.weight", "features.2.bias", "features.5.weight", "features.5.bias", "features.7.weight", "features.7.bias", "features.10.weight", "features.10.bias", "features.12.weight", "features.12.bias", "features.14.weight", "features.14.bias", "features.17.weight", "features.17.bias", "features.19.weight", "features.19.bias", "features.21.weight", "features.21.bias", "features.24.weight", "features.24.bias", "features.26.weight", "features.26.bias", "features.28.weight", "features.28.bias", "classifier.0.weight", "classifier.0.bias", "classifier.3.weight", "classifier.3.bias", "classifier.6.weight", "classifier.6.bias". 

could you help me ?thanks

**Comment by AceCoooool** [comment]
Which the pytorch version and torchvision version you use?
maybe you can use  链接: https://pan.baidu.com/s/1XbNjFJm5KmLJTFvU7uL4IQ 提取码: h3er  this link to download vgg_weights

**Comment by SoulCoderCN** [comment]
torch=0.4.1
torchvision=0.2.1
After using the pre-training VGG model you provided, the error was reported as follows:

Traceback (most recent call last):
  File "F:/DSS-pytorch-master2/main.py", line 95, in <module>
    main(config)
  File "F:/DSS-pytorch-master2/main.py", line 25, in main
    train.train()
  File "F:\DSS-pytorch-master2\solver.py", line 131, in train
    for i, data_batch in enumerate(self.train_loader):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_loader.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36\Lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by AceCoooool** [comment]
我这边Ubuntu下面没有这个问题。你看看是否是因为一些路径的问题呢？比如[Line 32](https://github.com/AceCoooool/DSS-pytorch/blob/159b6cf79e26f105b04df52c9ab054c409111bed/solver.py#L32)里面的路径在windows下应该为\而不是/
