### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by skysunsun** [AceCoooool/DSS-pytorch#17]
When I train my datasets,it comes 
Traceback (most recent call last):
  File "/home/skysun/modelchange/DSS-pytorch-master/main.py", line 96, in <module>
    main(config)
  File "/home/skysun/modelchange/DSS-pytorch-master/main.py", line 26, in main
    train.train()
  File "/home/skysun/modelchange/DSS-pytorch-master/solver.py", line 131, in train
    for i, data_batch in enumerate(self.train_loader):
  File "/home/skysun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/skysun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/skysun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/skysun/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/skysun/modelchange/DSS-pytorch-master/dataset.py", line 32, in __getitem__
    label = Image.open(self.label_path[item]).convert('L')
  File "/home/skysun/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/skysun/data/ship/Ship_Ground_True/002064.png'
But I  Actually have the file. Do you have the same problem? or make the datasets have some detail？

**Comment by skysunsun** [comment]
I'm so sorry.   I made a miss error!
